export const projects = [
  {
    id: 1,
    title: "Feyer",
    type: "React",
    logo: "/image/feyer.png",
    icon: "/icons/react.svg",
    link: "https://feyer.vercel.app",
  },
  {
    id: 2,
    title: "Mina",
    type: "Angular",
    logo: "/image/mina.png",
    icon: "/icons/angular-icon.svg",
    link: "https://mina-iota.vercel.app",
  },

  {
    id: 3,
    title: "Movie-App",
    type: "React",
    logo: "/image/movie-app.png",
    icon: "/icons/react.svg",
    link: "https://now-movie.vercel.app",
  },
  {
    id: 4,
    title: "Random-Number-Generator",
    type: "React",
    logo: "/image/random-number-generator.png",
    icon: "/icons/react.svg",
    link: "https://random-number-generator-seven-rho.vercel.app",
  },
  {
    id: 5,
    title: "Millionaire",
    type: "React",
    logo: "/image/millionaire.png",
    icon: "/icons/react.svg",
    link: "https://millionaire-application.vercel.app",
  },
  {
    id: 6,
    title: "Videp-Player",
    type: "DOM",
    logo: "/image/video-player.png",
    icon: "/icons/dom.png",
    link: "https://elgunsalmanov.github.io/Video-Player",
  },
  {
    id: 7,
    title: "Music-Player",
    type: "DOM",
    logo: "/image/music-player.png",
    icon: "/icons/dom.png",
    link: "https://elgunsalmanov.github.io/Music-Player",
  },
  {
    id: 8,
    title: "Expense-Tracker",
    type: "React",
    logo: "/image/expense-tracker.png",
    icon: "/icons/react.svg",
    link: "https://expense-tracker-one-dusky.vercel.app",
  },
  {
    id: 9,
    title: "Rock-Paper-Scissors",
    type: "DOM",
    logo: "/image/rock-paper-scissors.png",
    icon: "/icons/dom.png",
    link: "https://elgunsalmanov.github.io/Rock-Paper-Scissors",
  },
  {
    id: 10,
    title: "Guessing-Game",
    type: "DOM",
    logo: "/image/guessing-game.png",
    icon: "/icons/dom.png",
    link: "https://elgunsalmanov.github.io/Guessing-Game",
  },
];
